# These are supported funding model platforms

# If your project gains traction, consider adding your own sponsorship links
# Replace or remove the example links below with your own

# github: [username]
# patreon: username
# open_collective: project
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://example.com']

# This template was created to help you build amazing serverless apps with Puter.js
# If this template helped you, consider:
# - Starring the repository: https://github.com/ludoplex/puter.js-github-pages-hosted-client-app-template
# - Sharing it with others who might benefit
# - Contributing improvements back to the template
